### ISSUE TITLE
embed article fields in the `Paraphraser` not `Search Engine`

### ISSUE THREAD

**Issue by AardhynLavender** [AI-News-Team/AI-News#64]
the search engine currently fetches all articles on startup, and generates its own index for searching, by fetching article names ( `article.search.domain` ).

The rewriter should do this instead, and the `article.search.domain` api should return the article keys, and the embeddings.

this means searches will be up to date with the latest scraped data.

## Tasks

- [x] rewriter steals the embedding logic from `/search` and adds it to the `Article` table. ( name, and the first few lines of the body should be embedded )
- [x] `article.search.domain` should return the article id's and the embeddings from the `Article` table
- [x] Search engine is simplified to just perform the semantic searching on the fetched data.
